Made the following changes:   (1) updated FNVECTOR_PARALLEL module to allow user to specify a different MPI communicator   (2) modified configure script to check if MPI_Comm_f2c() from MPI-2 is supported   (3) modified fortran_update.in to remove MPI communicator argument from call to FNVINITP*() if MPI_Comm_f2c() is NOT supported   (4) updated other files to reflect changes to FNVECTOR_PARALLEL module

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -478,7 +478,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CC_COMP CPP EGREP FGREP F77 FFLAGS ac_ct_F77 F77_COMP FLIBS CXX CXXFLAGS ac_ct_CXX CXX_COMP CXXCPP MPICC_COMP MPIF77_COMP MPICXX_COMP LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP LIBTOOL COMPILER_PREFIX LINKER_PREFIX MPICC MPICXX MPIF77 MPI_INC_DIR MPI_LIB_DIR MPI_LIBS MPI_FLAGS MODULES NVEC_MODULES EXAMPLE_MODULES FCMIX_ENABLED FLOAT_TYPE LIBTOOL_CMD LIBTOOL_DEPS F77_MANGLE_MACRO F77_CASE F77_UNDERSCORES PRECISION_LEVEL GENERIC_MATH_LIB LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os SET_MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CC_COMP CPP EGREP FGREP F77 FFLAGS ac_ct_F77 F77_COMP FLIBS CXX CXXFLAGS ac_ct_CXX CXX_COMP CXXCPP MPICC_COMP MPIF77_COMP MPICXX_COMP LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP LIBTOOL COMPILER_PREFIX LINKER_PREFIX MPICC MPICXX MPIF77 MPI_INC_DIR MPI_LIB_DIR MPI_LIBS MPI_FLAGS MODULES NVEC_MODULES EXAMPLE_MODULES FCMIX_ENABLED FLOAT_TYPE LIBTOOL_CMD LIBTOOL_DEPS F77_MANGLE_MACRO F77_CASE F77_UNDERSCORES PRECISION_LEVEL GENERIC_MATH_LIB F77_MPI_COMM_F2C LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1823,6 +1823,7 @@ F77_CASE=""
 F77_UNDERSCORES=""
 PRECISION_LEVEL=""
 GENERIC_MATH_LIB=""
+F77_MPI_COMM_F2C=""
 
 
 
@@ -6978,7 +6979,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6981:" \
+echo "$as_me:6982:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7429,7 +7430,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7432: \"$ac_link\") >&5
+(eval echo $as_me:7433: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7511,7 +7512,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7514: \"$ac_link\") >&5
+(eval echo $as_me:7515: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9269,6 +9270,219 @@ rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 else
   MPI_C_COMP_OK="no"
+fi
+
+# Restore CPPFLAGS, LDFLAGS and LIBS
+CPPFLAGS="${SAVED_CPPFLAGS}"
+LDFLAGS="${SAVED_LDFLAGS}"
+LIBS="${SAVED_LIBS}"
+
+
+fi
+
+# Determine if MPI_Comm_f2c() from MPI-2 is supported
+if test "X${MPI_C_COMP_OK}" = "Xyes"; then
+
+
+# Determine if MPI implementation used to build SUNDIALS supports the
+# MPI_Comm_f2c() routine:
+#   (1) NO  : FNVECTOR_PARALLEL module will NOT allow user to specify
+#             an MPI communicator and MPI_COMM_WORLD will be used
+#   (2) YES : FNVECTOR_PARALLEL module will allow user to specify
+#             an MPI communicator
+# Provide variable description templates for config.hin and config.h files
+# Required by autoheader utility
+
+
+
+# Save copies of CPPFLAGS, LDFLAGS and LIBS (preserve information)
+# Temporarily overwritten so we can test MPI implementation
+SAVED_CPPFLAGS="${CPPFLAGS}"
+SAVED_LDFLAGS="${LDFLAGS}"
+SAVED_LIBS="${LIBS}"
+
+# Determine location of MPI header files (find MPI include directory)
+MPI_EXISTS="yes"
+
+# MPI include directory was NOT explicitly specified so check if MPI root
+# directory was given by user
+if test "X${MPI_INC_DIR}" = "X"; then
+  # MPI root directory was NOT given so issue a warning message
+  if test "X${MPI_ROOT_DIR}" = "X"; then
+    MPI_EXISTS="no"
+    { echo "$as_me:$LINENO: WARNING: cannot find MPI implementation files" >&5
+echo "$as_me: WARNING: cannot find MPI implementation files" >&2;}
+    echo ""
+    echo "   Unable to find MPI implementation files."
+    echo ""
+    echo "   Try using --with-mpicc to specify a MPI-C compiler script,"
+    echo "   --with-mpi-incdir, --with-mpi-libdir and --with-mpi-libs"
+    echo "   to specify the locations of all relevant MPI files, or"
+    echo "   --with-mpi-root to specify the base installation directory"
+    echo "   of the MPI implementation to be used."
+    echo ""
+    echo "   Disabling FNVECTOR_PARALLEL support for user-specified"
+    echo "   MPI communicator..."
+    echo ""
+  # MPI root directory was given so set MPI_INC_DIR accordingly
+  # Update CPPFLAGS
+  else
+    MPI_INC_DIR="${MPI_ROOT_DIR}/include"
+    if test "X${CPPFLAGS}" = "X"; then
+      CPPFLAGS="-I${MPI_INC_DIR}"
+    else
+      CPPFLAGS="${CPPFLAGS} -I${MPI_INC_DIR}"
+    fi
+    # Add MPI_FLAGS if non-empty
+    if test "X${MPI_FLAGS}" = "X"; then
+      CPPFLAGS="${CPPFLAGS}"
+    else
+      CPPFLAGS="${CPPFLAGS} ${MPI_FLAGS}"
+    fi
+  fi
+# MPI include directory was specified so update CPPFLAGS
+else
+  if test "X${CPPFLAGS}" = "X"; then
+    CPPFLAGS="-I${MPI_INC_DIR}"
+  else
+    CPPFLAGS="${CPPFLAGS} -I${MPI_INC_DIR}"
+  fi
+  # Add MPI_FLAGS if non-empty
+  if test "X${MPI_FLAGS}" = "X"; then
+    CPPFLAGS="${CPPFLAGS}"
+  else
+    CPPFLAGS="${CPPFLAGS} ${MPI_FLAGS}"
+  fi
+fi
+
+# Only continue if found an MPI implementation
+if test "X${MPI_EXISTS}" = "Xyes"; then
+
+  # Determine location of MPI libraries
+  # MPI library directory was NOT specified by user so set based upon MPI_ROOT_DIR
+  # Update LDFLAGS
+  if test "X${MPI_LIB_DIR}" = "X"; then
+    MPI_LIB_DIR="${MPI_ROOT_DIR}/lib"
+    if test "X${LDFLAGS}" = "X"; then
+      LDFLAGS="-L${MPI_LIB_DIR}"
+    else
+      LDFLAGS="${LDFLAGS} -L${MPI_LIB_DIR}"
+    fi
+  # MPI library directory was specified so update LDFLAGS
+  else
+    if test "X${LDFLAGS}" = "X"; then
+      LDFLAGS="-L${MPI_LIB_DIR}"
+    else
+      LDFLAGS="${LDFLAGS} -L${MPI_LIB_DIR}"
+    fi
+  fi
+
+  # Check if user specified which MPI libraries must be included
+  # If no libraries are given, then assume libmpi.[a/so] exists
+  if test "X${MPI_LIBS}" = "X"; then
+    MPI_LIBS="-lmpi"
+    if test "X${LIBS}" = "X"; then
+      LIBS="${MPI_LIBS}"
+    else
+      LIBS="${LIBS} ${MPI_LIBS}"
+    fi
+  # MPI libraries were specified so update LIBS
+  else
+    if test "X${LIBS}" = "X"; then
+      LIBS="${MPI_LIBS}"
+    else
+      LIBS="${LIBS} ${MPI_LIBS}"
+    fi
+  fi
+
+  # Since AC_LINK_IFELSE uses CC, set CC = MPICC if using
+  # an MPI compiler script
+  if test "X${USE_MPICC_SCRIPT}" = "Xyes"; then
+    SAVED_CC="${CC}"
+    CC="${MPICC_COMP}"
+  fi
+
+  # Check if MPI implementation supports MPI_Comm_f2c() from
+  # MPI-2 specification
+  echo "$as_me:$LINENO: checking for MPI_Comm_f2c from MPI-2" >&5
+echo $ECHO_N "checking for MPI_Comm_f2c from MPI-2... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "mpi.h"
+int
+main ()
+{
+
+      int c;
+      char **v;
+      MPI_Comm C_comm;
+      MPI_Init(&c, &v);
+      C_comm = MPI_Comm_f2c((MPI_Fint) 1);
+      MPI_Finalize();
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+   cat >>confdefs.h <<\_ACEOF
+#define SUNDIALS_MPI_COMM_F2C 1
+_ACEOF
+
+   F77_MPI_COMM_F2C="#define SUNDIALS_MPI_COMM_F2C 1"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+   cat >>confdefs.h <<\_ACEOF
+#define SUNDIALS_MPI_COMM_F2C 0
+_ACEOF
+
+   F77_MPI_COMM_F2C="#define SUNDIALS_MPI_COMM_F2C 0"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+  # Reset CC if necessary
+  if test "X${USE_MPICC_SCRIPT}" = "Xyes"; then
+    CC="${SAVED_CC}"
+  fi
+
+else
+  cat >>confdefs.h <<\_ACEOF
+#define SUNDIALS_MPI_COMM_F2C 0
+_ACEOF
+
+  F77_MPI_COMM_F2C="#define SUNDIALS_MPI_COMM_F2C 0"
 fi
 
 # Restore CPPFLAGS, LDFLAGS and LIBS
@@ -11194,7 +11408,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 11197 "configure"' > conftest.$ac_ext
+  echo '#line 11411 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11752,7 +11966,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:11755: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:11969: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -13678,7 +13892,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13681 "configure"
+#line 13895 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13776,7 +13990,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13779 "configure"
+#line 13993 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14663,6 +14877,7 @@ fi
 
 
 # Substitute variables
+
 
 
 
@@ -15609,6 +15824,7 @@ s,@F77_CASE@,$F77_CASE,;t t
 s,@F77_UNDERSCORES@,$F77_UNDERSCORES,;t t
 s,@PRECISION_LEVEL@,$PRECISION_LEVEL,;t t
 s,@GENERIC_MATH_LIB@,$GENERIC_MATH_LIB,;t t
+s,@F77_MPI_COMM_F2C@,$F77_MPI_COMM_F2C,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
