Pull request #482: Feature/sphinx docs
Merge in SUNDIALS/sunrepo from feature/sphinx-docs to develop

Squashed commit of the following:

commit 633c6d59152d93cf3eb474995d0dc5bd34a86ff7
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Tue Dec 14 08:07:18 2021 -0800

    correct CVODES guide UCRL number

commit e9f0e1ae3019fc99693213fcde0756809a9aeebc
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Tue Dec 14 07:56:41 2021 -0800

    various IDAS ADJ doc fixes

commit 9dded093e43597ae4b609d9db5246059904cb376
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 13:46:01 2021 -0800

    various doc fixes

commit 4e5cdbd15c5cbd905c17f6f10b5316eed462e006
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 13:30:49 2021 -0800

    minor org cleanup

commit b773beec9c76e6bd56a7d584643bc09b3b587b2c
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 13:30:34 2021 -0800

    minor equation udpates

commit 281f470e5f36f11f769e961230f00f3d0af039b9
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 12:59:15 2021 -0800

    relocate note

commit 6314731bc28651638f1c5317b0e3a35038951d25
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 12:48:05 2021 -0800

    fix equation numbering

commit 8fffd8e010505a1d34d3c5fc7538c2c31c83a4fa
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 12:30:22 2021 -0800

    add missing paragraph

commit 01d7f0d2240ad291b13d8678aed1cf49c9d366e5
Merge: d9d3ab8b6 bdb352ddf
Author: Balos, Cody Joe <balos1@llnl.gov>
Date:   Mon Dec 13 12:24:56 2021 -0800

    Merge remote-tracking branch 'origin/feature/sphinx-docs' into feature/sphinx-docs

commit d9d3ab8b6ebf5b6f8b3a8d14cbed9f56b1ff48f4
Author: Balos, Cody Joe <balos1@llnl.gov>
Date:   Mon Dec 13 12:24:46 2021 -0800

    add gpu paper

commit bdb352ddfb2dbc04522b63e81086551c0b6003cb
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 11:43:50 2021 -0800

    fix License section in non-superbuilds

commit 5f5e9043db5b809d8f7f170ff5309f05356cebae
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 10:54:59 2021 -0800

    fix contributors in IDAS

commit 01c614ed7739658ea8125d0524b4838d24a63a1e
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 10:11:50 2021 -0800

    hide toctree on main landing page

commit 5ca69b808181b19a8aee3a5e98f8666ead7b18ec
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 08:41:03 2021 -0800

    update CHANGELOG with new vector ops

commit 60f6452ca8459395a9c9b7fae37968d52f4663a4
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Dec 13 08:30:17 2021 -0800

    fix typo

commit 9b7b20442b0e523f3d5794118ce1dec6484b4985
Author: Balos, Cody Joe <balos1@llnl.gov>
Date:   Mon Dec 13 10:00:08 2021 -0800

    turn on sphinx Werror for package docs (except KINSOL because it has referecne warnings due to ifconfig and the SUNNonlinearsolver sections)

commit 605f8581650b8489d05fd5c063cc9d4b3f66f4f2
Author: Balos, Cody Joe <balos1@llnl.gov>
Date:   Mon Dec 13 09:56:37 2021 -0800

    add package specific interface section to shared class chapters

commit 989028842a3ac69909ce6f1ba0a3e12b7166eaf3
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Sun Dec 12 22:59:05 2021 -0800

    fix GPU ifconfig for non-super builds

commit e4b9f25b00a5c4b4d9019f27a9517e2e12f7eff2
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Sun Dec 12 21:19:34 2021 -0800

    fix GetSensStats warnings

commit 4a0673d7001770875d489afe4eef0a54f67cc29c
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Sun Dec 12 20:24:38 2021 -0800

    remove duplicate contexts

... and 745 more commits

diff --git a/scripts/tarscript b/scripts/tarscript
--- a/scripts/tarscript
+++ b/scripts/tarscript
@@ -1,9 +1,10 @@
 #!/bin/bash
 #
 # File tarscript: Script to build SUNDIALS tar-files.
-# Author: Radu Serban @ LLNL
-# Version of 08 August 2003
-#
+# Author: Radu Serban, David J. Gardner, Cody J. Balos @ LLNL
+
+# Exit immediately if a command fails
+set -e
 
 #==============================================================================
 #
@@ -171,9 +172,9 @@ cd ..
 sundialsdir=`pwd`
 
 # Location of tarballs
-\rm -rf tarballs || exit 1
-mkdir tarballs   || exit 1
-cd tarballs      || exit 1
+\rm -rf tarballs
+mkdir tarballs
+cd tarballs
 rootdir=`pwd`
 
 # Location of source for tarballs
@@ -184,14 +185,14 @@ tmpdir=$rootdir/tmp_dir
 #---------------------------
 echo -e "\n--- Create temporary directory ---"
 echo "copy $sundialsdir to $rootdir/$tmpdir"
-rm -rf $tmpdir         || exit 1
-mkdir $tmpdir          || exit 1
-mkdir $tmpdir/scripts  || exit 1
-mkdir $tmpdir/include  || exit 1
-mkdir $tmpdir/src      || exit 1
-mkdir $tmpdir/examples || exit 1
+rm -rf $tmpdir
+mkdir $tmpdir
+mkdir $tmpdir/scripts
+mkdir $tmpdir/include
+mkdir $tmpdir/src
+mkdir $tmpdir/examples
 if [ $doc = "T" ]; then
-    mkdir $tmpdir/doc  || exit 1
+    mkdir $tmpdir/doc
 fi
 
 #----------------------------------
@@ -199,59 +200,50 @@ fi
 # and create additional files as needed
 #----------------------------------
 
-cp $sundialsdir/LICENSE $tmpdir/             || exit 1
-cp $sundialsdir/NOTICE $tmpdir/              || exit 1
-cp $sundialsdir/README.md $tmpdir/           || exit 1
-cp $sundialsdir/CONTRIBUTING.md $tmpdir/     || exit 1
-cp $sundialsdir/CMakeLists.txt $tmpdir/      || exit 1
+cp $sundialsdir/CHANGELOG.md $tmpdir/
+cp $sundialsdir/CMakeLists.txt $tmpdir/
+cp $sundialsdir/CONTRIBUTING.md $tmpdir/
+cp $sundialsdir/LICENSE $tmpdir/
+cp $sundialsdir/NOTICE $tmpdir/
+cp $sundialsdir/README.md $tmpdir/
+cp $sundialsdir/.readthedocs.yaml $tmpdir/
 
 # Make install guide and copy to $tmpdir
 if [ $doc = "T" ]; then
     echo -e "--- SUNDIALS Common Installation documentation"
-    cd $sundialsdir/doc/sundials || exit 1
-
-    # cleanup, make install guide, copy, and cleanup
-    make QUIET= purge    || exit 1
-    make QUIET= in_g_pdf || exit 1
-    cp install_guide.pdf $tmpdir/INSTALL_GUIDE.pdf || exit 1
-    make QUIET= purge    || exit 1
-
+    cd $sundialsdir/doc/install_guide
+    make clean
+    make latexpdf
+    cp build/latex/INSTALL_GUIDE.pdf $tmpdir/INSTALL_GUIDE.pdf
     cd -
 fi
 
-cp -r $sundialsdir/benchmarks $tmpdir/ || exit 1
-cp -r $sundialsdir/cmake $tmpdir/      || exit 1
-cp -r $sundialsdir/test $tmpdir/       || exit 1
+cp -r $sundialsdir/benchmarks $tmpdir/
+cp -r $sundialsdir/cmake $tmpdir/
+cp -r $sundialsdir/test $tmpdir/
 
-cp -r $sundialsdir/include/sundials $tmpdir/include/     || exit 1
-cp -r $sundialsdir/include/nvector $tmpdir/include/      || exit 1
-cp -r $sundialsdir/include/sunmatrix $tmpdir/include/    || exit 1
-cp -r $sundialsdir/include/sunmemory $tmpdir/include/    || exit 1
-cp -r $sundialsdir/include/sunlinsol $tmpdir/include/    || exit 1
-cp -r $sundialsdir/include/sunnonlinsol $tmpdir/include/ || exit 1
+cp -r $sundialsdir/include/sundials $tmpdir/include/
+cp -r $sundialsdir/include/nvector $tmpdir/include/
+cp -r $sundialsdir/include/sunmatrix $tmpdir/include/
+cp -r $sundialsdir/include/sunmemory $tmpdir/include/
+cp -r $sundialsdir/include/sunlinsol $tmpdir/include/
+cp -r $sundialsdir/include/sunnonlinsol $tmpdir/include/
 
-cp    $sundialsdir/src/CMakeLists.txt $tmpdir/src/ || exit 1
-cp -r $sundialsdir/src/sundials $tmpdir/src/       || exit 1
-cp -r $sundialsdir/src/nvector $tmpdir/src/        || exit 1
-cp -r $sundialsdir/src/sunmatrix $tmpdir/src/      || exit 1
-cp -r $sundialsdir/src/sunmemory $tmpdir/src/      || exit 1
-cp -r $sundialsdir/src/sunlinsol $tmpdir/src/      || exit 1
-cp -r $sundialsdir/src/sunnonlinsol $tmpdir/src/   || exit 1
+cp    $sundialsdir/src/CMakeLists.txt $tmpdir/src/
+cp -r $sundialsdir/src/sundials $tmpdir/src/
+cp -r $sundialsdir/src/nvector $tmpdir/src/
+cp -r $sundialsdir/src/sunmatrix $tmpdir/src/
+cp -r $sundialsdir/src/sunmemory $tmpdir/src/
+cp -r $sundialsdir/src/sunlinsol $tmpdir/src/
+cp -r $sundialsdir/src/sunnonlinsol $tmpdir/src/
 
-cp    $sundialsdir/examples/CMakeLists.txt $tmpdir/examples/         || exit 1
-cp -r $sundialsdir/examples/utilities $tmpdir/examples/               || exit 1
-cp -r $sundialsdir/examples/nvector $tmpdir/examples/                || exit 1
-cp -r $sundialsdir/examples/sunmatrix $tmpdir/examples/              || exit 1
-cp -r $sundialsdir/examples/sunlinsol $tmpdir/examples/              || exit 1
-cp -r $sundialsdir/examples/sunnonlinsol $tmpdir/examples/           || exit 1
-cp -r $sundialsdir/examples/templates $tmpdir/examples/              || exit 1
-
-#cd $tmpdir
-#echo -e "\n--- Generate configure script ---"
-#aclocal --force
-#autoconf --force -o configure configure.ac
-#autoheader --force
-#cd -
+cp    $sundialsdir/examples/CMakeLists.txt $tmpdir/examples/
+cp -r $sundialsdir/examples/utilities $tmpdir/examples/
+cp -r $sundialsdir/examples/nvector $tmpdir/examples/
+cp -r $sundialsdir/examples/sunmatrix $tmpdir/examples/
+cp -r $sundialsdir/examples/sunlinsol $tmpdir/examples/
+cp -r $sundialsdir/examples/sunnonlinsol $tmpdir/examples/
+cp -r $sundialsdir/examples/templates $tmpdir/examples/
 
 # Don't release MATLAB until brought current with new version(s)
 #if [ $do_sundials = "T" ]; then
@@ -259,112 +251,66 @@ cp -r $sundialsdir/examples/templates $tmpdir/examples/              || exit 1
 #    cp -r $sundialsdir/sundialsTB/doc $tmpdir/doc/sundialsTB
 #fi
 
+mkdir -p $tmpdir/doc
+cp -r $sundialsdir/doc/shared $tmpdir/doc
+cp -r $sundialsdir/doc/superbuild $tmpdir/doc
+cp -r $sundialsdir/doc/requirements.txt $tmpdir/doc
+
 if [ $do_sundials = "T" -o $do_arkode = "T" ]; then
-    cp -r $sundialsdir/include/arkode $tmpdir/include/   || exit 1
-    cp -r $sundialsdir/src/arkode $tmpdir/src/           || exit 1
-    cp -r $sundialsdir/examples/arkode $tmpdir/examples/ || exit 1
+    cp -r $sundialsdir/include/arkode $tmpdir/include/
+    cp -r $sundialsdir/src/arkode $tmpdir/src/
+    cp -r $sundialsdir/examples/arkode $tmpdir/examples/
+    mkdir -p $tmpdir/doc/arkode
+    cp -r $sundialsdir/doc/arkode/guide $tmpdir/doc/arkode
     if [ $doc = "T" ]; then
         echo -e "--- ARKODE documentation"
-        mkdir $tmpdir/doc/arkode
-        cd $sundialsdir/doc/arkode/guide || exit 1
-        make clean     || exit 1
-        make latexpdf  || exit 1
-        cp build/latex/ark_guide.pdf $tmpdir/doc/arkode/. || exit 1
+        cd $sundialsdir/doc/arkode/guide
+        make clean
+        make latexpdf
+        cp build/latex/ark_guide.pdf $tmpdir/doc/arkode/
         cd -
-        cd $sundialsdir/doc/arkode/examples || exit 1
-        make clean     || exit 1
-        make latexpdf  || exit 1
-        cp build/latex/ark_examples.pdf $tmpdir/doc/arkode/. || exit 1
+        cd $sundialsdir/doc/arkode/examples
+        make clean
+        make latexpdf
+        cp build/latex/ark_examples.pdf $tmpdir/doc/arkode/
         cd -
     fi
 fi
 
-if [ $do_sundials = "T" -o $do_cvode = "T" ]; then
-    cp -r $sundialsdir/include/cvode $tmpdir/include/   || exit 1
-    cp -r $sundialsdir/src/cvode $tmpdir/src/           || exit 1
-    cp -r $sundialsdir/examples/cvode $tmpdir/examples/ || exit 1
+declare -a packages=('cvode' 'cvodes' 'ida' 'idas' 'kinsol')
+for pkg in "${packages[@]}";
+do
+    do_package=do_${pkg}
+    if [ $do_sundials = "T" -o ${!do_package} = "T" ]; then
+        cp -r $sundialsdir/include/$pkg $tmpdir/include/
+        cp -r $sundialsdir/src/$pkg $tmpdir/src/
+        cp -r $sundialsdir/examples/$pkg $tmpdir/examples/
+        mkdir -p $tmpdir/doc/$pkg
+        cp -r $sundialsdir/doc/$pkg/guide $tmpdir/doc/$pkg
+        if [ $doc = "T" ]; then
+            echo -e "--- ${pkg} documentation"
+            cd $sundialsdir/doc/$pkg/guide
+            make clean
+            make latexpdf
+            cp build/latex/*_guide.pdf $tmpdir/doc/$pkg/
+            cd -
+            cd $sundialsdir/doc/$pkg
+            make QUIET= ex_pdf
+            cp *_examples.pdf $tmpdir/doc/$pkg/
+            cd -
+        fi
+    fi
+done
+
+if [ $do_sundials = "T" ]; then
     if [ $doc = "T" ]; then
-        echo -e "--- CVODE documentation"
-        mkdir $tmpdir/doc/cvode
-        cd $sundialsdir/doc/cvode || exit 1
-        make QUIET= purge    || exit 1
-        make QUIET= ug_pdf   || exit 1
-        make QUIET= ex_pdf   || exit 1
-        cp cv_guide.pdf $tmpdir/doc/cvode/.    || exit 1
-        cp cv_examples.pdf $tmpdir/doc/cvode/. || exit 1
+        echo -e "--- super build of documentation"
+        cd $sundialsdir/doc/superbuild/
+        make clean
+        make html
         cd -
     fi
 fi
-
-if [ $do_sundials = "T" -o $do_cvodes = "T" ]; then
-    cp -r $sundialsdir/include/cvodes $tmpdir/include/   || exit 1
-    cp -r $sundialsdir/src/cvodes $tmpdir/src/           || exit 1
-    cp -r $sundialsdir/examples/cvodes $tmpdir/examples/ || exit 1
-    if [ $doc = "T" ]; then
-        echo -e "--- CVODES documentation"
-        mkdir $tmpdir/doc/cvodes
-        cd $sundialsdir/doc/cvodes || exit 1
-        make QUIET= purge     || exit 1
-        make QUIET= ug_pdf    || exit 1
-        make QUIET= ex_pdf    || exit 1
-        cp cvs_guide.pdf $tmpdir/doc/cvodes/.    || exit 1
-        cp cvs_examples.pdf $tmpdir/doc/cvodes/. || exit 1
-        cd -
-    fi
-fi
-
-if [ $do_sundials = "T" -o $do_ida = "T" ]; then
-    cp -r $sundialsdir/include/ida $tmpdir/include/   || exit 1
-    cp -r $sundialsdir/src/ida $tmpdir/src/           || exit 1
-    cp -r $sundialsdir/examples/ida $tmpdir/examples/ || exit 1
-    if [ $doc = "T" ]; then
-        echo -e "--- IDA documentation"
-        mkdir $tmpdir/doc/ida
-        cd $sundialsdir/doc/ida || exit 1
-        make QUIET= purge  || exit 1
-        make QUIET= ug_pdf || exit 1
-        make QUIET= ex_pdf || exit 1
-        cp ida_guide.pdf $tmpdir/doc/ida/.    || exit 1
-        cp ida_examples.pdf $tmpdir/doc/ida/. || exit 1
-        cd -
-    fi
-fi
-
-if [ $do_sundials = "T" -o $do_idas = "T" ]; then
-    cp -r $sundialsdir/include/idas $tmpdir/include/   || exit 1
-    cp -r $sundialsdir/src/idas $tmpdir/src/           || exit 1
-    cp -r $sundialsdir/examples/idas $tmpdir/examples/ || exit 1
-    if [ $doc = "T" ]; then
-        echo -e "--- IDAS documentation"
-        mkdir $tmpdir/doc/idas
-        cd $sundialsdir/doc/idas || exit 1
-        make QUIET= purge   || exit 1
-        make QUIET= ug_pdf  || exit 1
-        make QUIET= ex_pdf  || exit 1
-        cp idas_guide.pdf $tmpdir/doc/idas/.    || exit 1
-        cp idas_examples.pdf $tmpdir/doc/idas/. || exit 1
-        cd -
-    fi
-fi
-
-if [ $do_sundials = "T" -o $do_kinsol = "T" ]; then
-    cp -r $sundialsdir/include/kinsol $tmpdir/include/   || exit 1
-    cp -r $sundialsdir/src/kinsol $tmpdir/src/           || exit 1
-    cp -r $sundialsdir/examples/kinsol $tmpdir/examples/ || exit 1
-    if [ $doc = "T" ]; then
-        echo -e "--- KINSOL documentation"
-        mkdir $tmpdir/doc/kinsol
-        cd $sundialsdir/doc/kinsol || exit 1
-        make QUIET= purge     || exit 1
-        make QUIET= ug_pdf    || exit 1
-        make QUIET= ex_pdf    || exit 1
-        cp kin_guide.pdf $tmpdir/doc/kinsol/.    || exit 1
-        cp kin_examples.pdf $tmpdir/doc/kinsol/. || exit 1
-        cd -
-    fi
-fi
-
-
 
 #---------------------------
 # Create tar files
@@ -378,108 +324,107 @@ distrobase="$tmpdir"
 if [ $do_sundials = "T" ]; then
     echo -e "\n--- Generate SUNDIALS tarball ---"
 
-    mv $distrobase sundials-$SUN_VER || exit 1
+    mv $distrobase sundials-$SUN_VER
     distrobase="sundials-"$SUN_VER
     filename="sundials-"$SUN_VER
 
     tarfile=$filename".tar"
-    echo "$scriptdir/shared $tarfile $distrobase $doc $tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/arkode $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/cvode  $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/cvodes $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/ida    $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/idas   $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/kinsol $tarfile $distrobase $doc $tar || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/arkode $tarfile $distrobase $doc $tar
+    $scriptdir/cvode  $tarfile $distrobase $doc $tar
+    $scriptdir/cvodes $tarfile $distrobase $doc $tar
+    $scriptdir/ida    $tarfile $distrobase $doc $tar
+    $scriptdir/idas   $tarfile $distrobase $doc $tar
+    $scriptdir/kinsol $tarfile $distrobase $doc $tar
 
     ### Don't release MATLAB until brought current with new version(s)
     # $scriptdir/stb $tarfile $distrobase $doc $tar
 
-    gzip $tarfile || exit 1
+    gzip $tarfile
 fi
 
 # ARKODE
 if [ $do_arkode = "T" ]; then
     echo -e "\n--- Generate ARKODE tarball ---"
 
-    mv $distrobase arkode-$ARK_VER || exit 1
+    mv $distrobase arkode-$ARK_VER
     distrobase="arkode-"$ARK_VER
     filename="arkode-"$ARK_VER
 
     tarfile=$filename".tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/arkode $tarfile $distrobase $doc $tar || exit 1
-    gzip $tarfile || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/arkode $tarfile $distrobase $doc $tar
+    gzip $tarfile
 fi
 
 # CVODE
 if [ $do_cvode = "T" ]; then
     echo -e "\n--- Generate CVODE tarball ---"
 
-    mv $distrobase cvode-$CV_VER || exit 1
+    mv $distrobase cvode-$CV_VER
     distrobase="cvode-"$CV_VER
     filename="cvode-"$CV_VER
 
     tarfile=$filename".tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/cvode  $tarfile $distrobase $doc $tar || exit 1
-    gzip $tarfile || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/cvode  $tarfile $distrobase $doc $tar
+    gzip $tarfile
 fi
 
 # CVODES
 if [ $do_cvodes = "T" ]; then
     echo -e "\n--- Generate CVODES tarball ---"
 
-    mv $distrobase cvodes-$CVS_VER || exit 1
+    mv $distrobase cvodes-$CVS_VER
     distrobase="cvodes-"$CVS_VER
     filename="cvodes-"$CVS_VER
 
     tarfile=$filename".tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/cvodes $tarfile $distrobase $doc $tar || exit 1
-    gzip $tarfile || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/cvodes $tarfile $distrobase $doc $tar
+    gzip $tarfile
 fi
 
 # IDA
 if [ $do_ida = "T" ]; then
     echo -e "\n--- Generate IDA tarball ---"
 
-    mv $distrobase ida-$IDA_VER || exit 1
+    mv $distrobase ida-$IDA_VER
     distrobase="ida-"$IDA_VER
     filename="ida-"$IDA_VER
 
     tarfile=$filename".tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/ida    $tarfile $distrobase $doc $tar || exit 1
-    gzip $tarfile || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/ida    $tarfile $distrobase $doc $tar
+    gzip $tarfile
 fi
 
 # IDAS
 if [ $do_idas = "T" ]; then
     echo -e "\n--- Generate IDAS tarball ---"
 
-    mv $distrobase idas-$IDAS_VER || exit 1
+    mv $distrobase idas-$IDAS_VER
     distrobase="idas-"$IDAS_VER
     filename="idas-"$IDAS_VER
 
     tarfile=$filename".tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/idas   $tarfile $distrobase $doc $tar || exit 1
-    gzip $tarfile || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/idas   $tarfile $distrobase $doc $tar
+    gzip $tarfile
 fi
 
 # KINSOL
 if [ $do_kinsol = "T" ]; then
     echo -e "\n--- Generate KINSOL tarball ---"
 
-    mv $distrobase kinsol-$KIN_VER || exit 1
+    mv $distrobase kinsol-$KIN_VER
     distrobase="kinsol-"$KIN_VER
     filename="kinsol-"$KIN_VER
 
     tarfile=$filename".tar"
-    $scriptdir/shared $tarfile $distrobase $doc $tar || exit 1
-    $scriptdir/kinsol $tarfile $distrobase $doc $tar || exit 1
-    gzip $tarfile || exit 1
+    $scriptdir/shared $tarfile $distrobase $doc $do_sundials $tar
+    $scriptdir/kinsol $tarfile $distrobase $doc $tar
+    gzip $tarfile
 fi
 
 #---------------------------
