Merge pull request #427 in SUNDIALS/sunrepo from feature/sycl-vector to develop
Squashed commit of the following:

commit 99f1db138acb4a55371180965f02a3b93f1b87b6
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 28 14:17:06 2021 -0800

    update constructor docs

commit 0a9400345d0ad5ae863107a5f874711f07ac1371
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 28 10:58:51 2021 -0800

    update docs

commit ddd8b5c1567a6304d3324064693b148d97060c88
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 28 18:38:04 2021 +0000

    enable c++ examples if HIP is enabled

commit 75df041de378c613b76cc0ff6784a86708900968
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 28 18:32:22 2021 +0000

    fix typo

commit b226d886327cfc9d3253aad1318af01e1c41cc97
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 28 18:31:21 2021 +0000

    remove extra waits

commit 30a1b7c9d5bcaac657f31d0000367fb3519d8224
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 28 18:14:19 2021 +0000

    move queue input to end of constructor

commit 3ca012638193d5e144a084cc1a9f442ff9be742f
Merge: 38fa057de da7e3426c
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Jan 25 09:37:10 2021 -0800

    Merge branch 'develop' into feature/sycl-vector

commit 38fa057de62b84286ffc51ff452859909c4ad0b9
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Mon Jan 25 09:36:46 2021 -0800

    regen f2003 interfaces

commit 59c60b0d91caf9010ed6fe78cbb5d7a96f16a224
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Fri Jan 22 12:52:21 2021 -0800

    update comments

commit 1b9381235e6a1309fd1c8b8d1c9907a6d4363d43
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Fri Jan 22 12:42:49 2021 -0800

    update tarscript

commit 59b473bfe1f0e761d7cc1be1994f311716cf3b26
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Fri Jan 22 12:37:33 2021 -0800

    fix typo

commit 03eb9c588f6d0689aef2621060cffa235aa58d21
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Fri Jan 22 19:39:08 2021 +0000

    add test with custom memhelper

commit fc8c10d559ef46151372d3b8b0ce50e0b1edd812
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Fri Jan 22 17:47:10 2021 +0000

    cmake updates

commit fa62a0a56ae287698bb8f2e2676aee254ae8f379
Merge: 93733b32f 4c13e22a9
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Fri Jan 22 09:39:30 2021 -0800

    Merge branch 'develop' into feature/sycl-vector

    Conflicts:
      doc/arkode/guide/build/latex/ark_guide.tex

commit 93733b32f02286f6a818607610c3fa1e6bd78b80
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 21 22:59:48 2021 -0800

    update recent changes

commit 98ef5a76d2eae0b39ac226f6895e9517983434ab
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 21 22:57:37 2021 -0800

    doc updates

commit fb9633763e4cbb1f6f497a3b2a46c3f9c81e9f50
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 21 21:25:31 2021 -0800

    fix typos

commit e13426a334231e440b0bc348229dc6c4f5e1b37a
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 21 21:21:59 2021 -0800

    update tex sunmem docs

commit 66a3ae28db2af01ebe9d58128c80653091337b1f
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 21 20:59:51 2021 -0800

    doc fixes

commit 05ff910815d3a8de23f5be1861403869be7b1e49
Author: David J. Gardner <gardner48@llnl.gov>
Date:   Thu Jan 21 20:26:47 2021 -0800

    update vector ID table

... and 5 more commits

diff --git a/scripts/tarscript b/scripts/tarscript
--- a/scripts/tarscript
+++ b/scripts/tarscript
@@ -14,7 +14,7 @@
 function print_usage
 {
     # Location of tarballs
-    cd ../..
+    cd ..
     location=`pwd`
     cd -
 
@@ -28,7 +28,7 @@ function print_usage
     echo ""
     echo "Notes: If the module is not specified, all tarballs are created."
     echo "       This script must be executed from within its directory."
-    echo "       Tarballs will be created in $location"
+    echo "       Tarballs will be created in $location/tarballs"
     echo ""
     exit 1
 }
@@ -204,16 +204,19 @@ cp $sundialsdir/doc/Makefile.in $tmpdir/doc/ || exit 1
 cp $sundialsdir/CMakeLists.txt $tmpdir/      || exit 1
 
 # Make install guide and copy to $tmpdir
-echo -e "--- SUNDIALS Common Installation documentation"
-cd $sundialsdir/doc/sundials || exit 1
+if [ $doc = "T" ]; then
+    echo -e "--- SUNDIALS Common Installation documentation"
+    cd $sundialsdir/doc/sundials || exit 1
 
-# cleanup, make install guide, copy, and cleanup
-make QUIET= purge    || exit 1
-make QUIET= in_g_pdf || exit 1
-cp $sundialsdir/doc/sundials/install_guide.pdf $tmpdir/INSTALL_GUIDE.pdf || exit 1
-make QUIET= purge    || exit 1
+    # cleanup, make install guide, copy, and cleanup
+    make QUIET= purge    || exit 1
+    make QUIET= in_g_pdf || exit 1
+    cp $sundialsdir/doc/sundials/install_guide.pdf $tmpdir/INSTALL_GUIDE.pdf || exit 1
+    make QUIET= purge    || exit 1
 
-cd -
+    cd -
+fi
+
 cp -r $sundialsdir/cmake $tmpdir/ || exit 1
 cp -r $sundialsdir/test $tmpdir/   || exit 1
 
